### ISSUE TITLE
عند إضافة معلم من قبل الإداري و قبولة من قبل الأخصائي لا ينتقل من قيد الموافقة إلى الموظفين 

### ISSUE THREAD

**Issue by nooraheji** [samaryahya/Quran#14]
عند إضافة معلم من قبل الإداري و قبولة من قبل الأخصائي لا ينتقل من قيد الموافقة إلى الموظفين 
ولا يظهر للإداري في بيانات الموظفين

**Comment by samaryahya** [comment]
المشكلة موجودة عند الاضافة حيث لا يتم اضافة مركز للموظف
