### ISSUE TITLE
عند طلب الطالبة لمادتين مختلفتين ( تلاوة + حفظ ) عند نفس المعلمة

### ISSUE THREAD

**Issue by nooraheji** [samaryahya/Quran#24]
عند طلب الطالبة لمادتين مختلقتين ( تلاوة + حفظ ) عند نفس المعلمة ،، المشكلة تكمن في عند قيام المعلومة بتدخيل التصيل اليومي للطالب تظهر لها الطالبة مرتين
فغير موضح للمعلمة المادة

**Comment by samaryahya** [comment]
تم اضافة اسم المادة للرقم السكاني و الاسم من قائمة الطالب
