### ISSUE TITLE
عند غياب الطالبة لا توجد خاصية للمعلمة بتدوينها في التحصيل اليومي

### ISSUE THREAD

**Issue by nooraheji** [samaryahya/Quran#25]
تم توضيح المقترح في الهاتف

**Comment by samaryahya** [comment]
تم اضافة علامة للغياب في نفس الصفحة بحيث يتم ازالة الدرجة عند تفعيها و تةضع الدرجة مساوية لصفر كما تم تظليل جميع الحقول المطلوبة باللون الاحمر
