### ISSUE TITLE
هناك عدة مراكز لا يمكن فتح أيقونة التعديل وهي

### ISSUE THREAD

**Issue by nooraheji** [samaryahya/Quran#75]
1.	حلقات مسجد ابن رشد ( رقم المركز 277 وهو مركز مستقل ولكن غير نشط )
2.	عبدالله بن مسعود ( رقم المركز الرئيسي 109 ويوجد تحته 9 فروع ،، يرجى حذف جميع المراكز الأخرى بنفس الاسم  )
3.	حلقات جامع التوبة  ( رقم المركز 7 وهو مركز مستقل لا توجد تحته فروع )
4.	حوزة العلمين – السيد زينب ( رقم المركز 151 وهو مركز مستقل لا توجد تحته فروع )
5. حوزة العلمين – العلمين ( رقم المركز 154 )
6. حلقات جامع أحمد الظهراني للجاليات ( رقم المركز 196 )

**Comment by samaryahya** [comment]
لم اجد هذة المشكلة برجاء التحقق مرة اخرى
