### ISSUE TITLE
تم فصل جميع المراكز من جهتنا في القاعدة ماعذا المراكز التي أشتغلو الإداريات عليها تركناها لكم وهم

### ISSUE THREAD

**Issue by nooraheji** [samaryahya/Quran#77]
1.	حلقات مسجد الصحابة – نساء
2.	مركز أحمد بن سلمان – نساء
3.	مركز عبدالله بن أحمد الغتم - نساء
4.	مركز الشيخ عيسى بن علي – نساء
5.	محمود الكوهجي
6.	مركز شيخان و شريفة الفارسي

المطلوب:
 أولاً إضافة 4 مراكز جديدة تحت المسميات الآتية
 ثانياً نقل بيانات المراكز أعلاه من الفرع الرئيسي نساء إلى المركز الرئيسي الموضح أعلاه

**Comment by samaryahya** [comment]
تم اكمال نقل البيانات
